// JavaScript fallback for Go document_builder when Go WASM fails to load.
// This provides the same document generation functionality in pure JavaScript.
window.goDocumentBuilder = function(inputJson) {
    try {
        var input = JSON.parse(inputJson);
        var template = input.template || 'research_report';
        var title = input.title || 'Untitled';
        var nl = '\n';
        var md = '# ' + title + nl + nl;
        
        if (template === 'summary') {
            if (input.key_points) {
                input.key_points.forEach(function(p) { md += '- ' + p + nl; });
            }
            if (input.conclusion) { md += nl + input.conclusion + nl; }
        } else if (template === 'comparison') {
            if (input.items) {
                md += '| Item | Pros | Cons |' + nl + '|------|------|------|' + nl;
                input.items.forEach(function(item) {
                    md += '| ' + (item.name || '') + ' | ' + (item.pros || []).join(', ') + ' | ' + (item.cons || []).join(', ') + ' |' + nl;
                });
            }
            if (input.recommendation) { md += nl + '**Recommendation:** ' + input.recommendation + nl; }
        } else {
            if (input.sections) {
                input.sections.forEach(function(s) {
                    md += '## ' + (s.heading || '') + nl + nl + (s.content || '') + nl + nl;
                    if (s.data_table) {
                        var headers = s.data_table.headers || [];
                        md += '| ' + headers.join(' | ') + ' |' + nl;
                        md += '|' + headers.map(function() { return '---'; }).join('|') + '|' + nl;
                        (s.data_table.rows || []).forEach(function(row) {
                            md += '| ' + row.join(' | ') + ' |' + nl;
                        });
                        md += nl;
                    }
                });
            }
            if (input.citations) {
                md += '---' + nl + nl + '## References' + nl + nl;
                input.citations.forEach(function(c) {
                    md += '[' + c.id + '] [' + (c.title || c.url) + '](' + c.url + ')' + nl;
                });
            }
        }
        md += nl + '---' + nl + '*Generated by Amplifier Polyglot Agent*' + nl;
        return JSON.stringify({success: true, output: md});
    } catch (e) {
        return JSON.stringify({success: false, error: e.message});
    }
};
window.goWasmReady = true;
